services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.8
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  timescaledb:
      image: timescale/timescaledb:latest-pg16
      container_name: timescaledb
      ports:
        - "5434:5432"
      environment:
        POSTGRES_DB: flightstream
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password

  redis:
    image: redis:8.6.2
    container_name: redis
    ports:
    - "6379:6379"